# .pre-commit-config.yaml
#
#  Pre-commit configuration file
#  To install pre-commit executable command via pip: pip install pre-commit
#  To install the git hooks, run: pre-commit install --install-hooks
#  See https://pre-commit.com/ for more details

default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
        name: '[Fmt]  Fix end of files'
      - id: trailing-whitespace
        name: '[Fmt]  Fix trailing whitespaces'

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.47.0
    hooks:
    - id: markdownlint
      name: '[Lint] Markdownlint (*.md)'
      args: ["--config", ".markdownlint.yaml"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: '[Fmt]  Prettier (*.json)'
        types_or: [json]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        name: '[Lint] check-yaml (*.yml,*.yaml)'
        types_or: [yaml]

  - repo: https://github.com/psf/black
    rev: 26.1.0
    hooks:
      - id: black
        name: '[Fmt]  Black (*.py)'

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        name: '[Lint] Flake8 (*.py)'

  - repo: https://github.com/checkmake/checkmake
    rev: v0.3.0
    hooks:
    - id: checkmake
      name: '[Lint] checkmake (Makefile)'

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.5
    hooks:
      - id: terraform_fmt
        name: '[Fmt]  Terraform fmt'
      - id: terraform_validate
        name: '[Lint] Terraform validate'
      - id: terraform_tflint
        name: '[Lint] Terraform tflint'
